const RUNGS=[1000,2000,4000,8000,16000,32000,64000,128000,256000,512000,1000000];
const LABELS=["Start","2x","4x","8x","16x","32x","64x","128x","256x","512x","1000x"];
const KEY="litdex.v1";
const API="https://mainnet.zklighter.elliot.ai/api/v1";
const todayISO=()=>new Date().toISOString().slice(0,10);
const fmt=(n,d=0)=>{const x=Number(n)||0,a=Math.abs(x);if(a>=1e6)return(x/1e6).toFixed(2)+"M";if(a>=1e4)return(x/1e3).toFixed(1)+"K";return x.toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});};
const money=n=>"$"+(Number(n)||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const signed=n=>(n>=0?"+":"")+money(n);
const cls=n=>n>=0?"up":"down";
function seedDays(days=120){const out={};let eq=1000;const start=new Date();start.setDate(start.getDate()-(days-1));for(let i=0;i<days;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=d.toISOString().slice(0,10);const weekend=d.getDay()===0||d.getDay()===6;if(weekend&&Math.random()<0.55){out[iso]={pnl:0,trades:0,note:""};continue;}const edge=(Math.random()-0.46)*0.035;const pnl=Math.round(eq*edge*100)/100;const trades=weekend?Math.floor(Math.random()*3):1+Math.floor(Math.random()*6);eq=Math.max(400,eq+pnl);out[iso]={pnl,trades,note:pnl>eq*0.02?"runner":pnl<-eq*0.02?"cut loser":""};}return{days:out,equity:Math.round(eq*100)/100};}
function defaultState(){const seeded=seedDays(130);return{start:1000,equity:seeded.equity,realized:Math.round((seeded.equity-1000)*0.62),unrealized:Math.round((seeded.equity-1000)*0.38),deposits:1000,address:"",accountIndex:"",days:seeded.days,positions:[{sym:"ETH",side:"long",size:1.8,entry:2490,mark:2641.3,lev:8},{sym:"LIT",side:"long",size:620,entry:4.12,mark:4.83,lev:4},{sym:"SOL",side:"short",size:40,entry:118.4,mark:110.53,lev:5},{sym:"BTC",side:"long",size:0.04,entry:79820,mark:81188,lev:6}],tape:{LIT:4.83,BTC:81188,ETH:2641,SOL:110.53,HYPE:93.66}};} 
function load(){try{const raw=localStorage.getItem(KEY);if(raw)return JSON.parse(raw);}catch(e){}const s=defaultState();save(s);return s;}
function save(s){localStorage.setItem(KEY,JSON.stringify(s));}
let S=load();
function rungState(eq){let done=0;for(let i=0;i<RUNGS.length;i++)if(eq>=RUNGS[i])done=i;const floor=RUNGS[done];const next=RUNGS[Math.min(done+1,RUNGS.length-1)];const prog=next===floor?1:Math.min(1,Math.max(0,(eq-floor)/(next-floor)));return{done,floor,next,prog,multiple:eq/S.start};}
function dayList(){return Object.entries(S.days).map(([date,v])=>({date,...v})).sort((a,b)=>a.date.localeCompare(b.date));}
function rangePnl(n){return dayList().slice(-n).reduce((a,d)=>a+(d.pnl||0),0);}
function sparkSVG(values){if(!values.length)return"";const w=320,h=72,p=4;const min=Math.min(...values),max=Math.max(...values);const span=Math.max(1e-6,max-min);const pts=values.map((v,i)=>{const x=p+(i/(values.length-1))*(w-2*p);const y=h-p-((v-min)/span)*(h-2*p);return x+","+y;}).join(" ");const last=values[values.length-1],first=values[0];const color=last>=first?"#C8F542":"#FF5B73";return '<svg class="spark" viewBox="0 0 '+w+' '+h+'" preserveAspectRatio="none"><polyline fill="none" stroke="'+color+'" stroke-width="2.2" points="'+pts+'"/></svg>';}
function equityCurve(){let eq=S.start;const arr=[eq];dayList().forEach(d=>{eq+=d.pnl||0;arr.push(eq);});return arr;}
function el(id){return document.getElementById(id);}
function renderHome(){const rs=rungState(S.equity);const d1=rangePnl(1),d7=rangePnl(7),d30=rangePnl(30);const curve=equityCurve();
el("s-home").innerHTML='<div class="hero"><div class="label">Account equity</div><div class="equity">'+money(S.equity)+'</div><div class="pnl '+cls(S.equity-S.start)+'">'+signed(S.equity-S.start)+' \u00b7 '+(S.equity/S.start).toFixed(2)+'x from $1K</div><div style="margin-top:12px">'+sparkSVG(curve.slice(-60))+'</div><div class="tiny" style="margin-top:8px">Double '+rs.done+' of 10 \u00b7 next '+money(rs.next)+' \u00b7 '+(rs.prog*100).toFixed(0)+'%</div><div class="bar" style="margin-top:8px"><i style="width:'+(rs.prog*100).toFixed(1)+'%"></i></div></div><div class="row" style="margin-top:10px"><div class="stat"><div class="label">Today</div><b class="'+cls(d1)+'">'+signed(d1)+'</b></div><div class="stat"><div class="label">7D</div><b class="'+cls(d7)+'">'+signed(d7)+'</b></div><div class="stat"><div class="label">30D</div><b class="'+cls(d30)+'">'+signed(d30)+'</b></div></div><div class="card"><h3>Lighter tape</h3><div class="pillrow" id="tape"></div></div><div class="card"><h3>Open positions</h3>'+S.positions.map(p=>{const pnl=(p.side==="long"?1:-1)*(p.mark-p.entry)*p.size;const notional=p.mark*p.size;return '<div class="pos"><div><b>'+p.sym+'</b> <span class="tag '+p.side+'">'+p.side.toUpperCase()+' '+p.lev+'x</span><div class="tiny">'+p.size+' @ '+fmt(p.entry,p.entry<20?2:1)+'</div></div><div style="text-align:right"><div class="'+cls(pnl)+'">'+signed(pnl)+'</div><div class="tiny">'+money(notional)+'</div></div></div>';}).join("")+'</div><div class="card"><h3>Quick log today</h3><div class="grid2"><input id="qPnl" type="number" step="0.01" placeholder="PnL $" /><input id="qTrades" type="number" placeholder="Trades" /></div><button class="btn primary" style="margin-top:8px" onclick="logToday()">Save today\'s PnL</button></div>';
Object.entries(S.tape).forEach(([k,v])=>{const n=document.createElement("div");n.className="pill on";n.textContent=k+" "+(v<20?Number(v).toFixed(2):fmt(v,0));el("tape").appendChild(n);});}
function renderDouble(){const eq=S.equity;const rs=rungState(eq);const need=Math.max(0,rs.next-eq);const avg=rangePnl(30)/30;const days=avg>0?Math.ceil(need/avg):null;
el("s-double").innerHTML='<h2 class="sec">Double the bag</h2><div class="hero"><div class="label">Path from $1,000 to $1,000,000</div><div class="equity">'+rs.done+'<span style="font-size:18px;color:var(--muted)"> / 10 doubles</span></div><div class="muted">'+money(eq)+' \u00b7 '+rs.multiple.toFixed(2)+'x \u00b7 '+(need?money(need)+" to next double":"goal reached")+'</div><div class="bar" style="margin-top:12px"><i style="width:'+((Math.log2(Math.max(eq,1000)/1000)/10)*100).toFixed(1)+'%"></i></div><div class="tiny" style="margin-top:8px">'+(days?("At 30D pace (~"+signed(avg)+"/day) next double in ~"+days+" days"):"Need positive expectancy to project the next double")+'</div></div><div class="card"><h3>Simulate equity</h3><input id="sim" type="range" min="1000" max="1000000" step="100" value="'+Math.min(1000000,Math.max(1000,eq))+'" oninput="previewSim(this.value)" /><div class="tiny" id="simOut">Drag to preview any level on the ladder</div></div><div class="card"><h3>The 10 doubles</h3><div class="ladder"><div class="track"><div class="trackfill" style="height:'+(rs.done/(RUNGS.length-1)*100)+'%"></div></div>'+RUNGS.map((amt,i)=>{const locked=eq>=amt;const left=Math.max(0,amt-eq);return '<div class="rung" onclick="focusRung('+i+')"><div class="node '+(locked?"done":"")+((!locked&&i===rs.done+1)?" now":"")+'"></div><div><div class="amt">'+money(amt)+'</div><div class="sub">'+LABELS[i]+' '+(locked?"cleared":(left?money(left)+" remaining":""))+'</div></div><div class="tiny">'+(locked?"\u2713":(i===rs.done+1?(rs.prog*100).toFixed(0)+"%":""))+'</div></div>';}).join("")+'</div></div><div class="card"><h3>What a double actually requires</h3><p class="muted">Ten clean doubles turn $1,000 into $1,024,000. You do not need a 1,000x trade. You need 10 sequential 100% cycles.</p></div>';}
function previewSim(v){const n=Number(v);const r=rungState(n);el("simOut").textContent=money(n)+" \u00b7 double "+r.done+"/10 \u00b7 "+(r.prog*100).toFixed(0)+"% to "+money(r.next);}
function focusRung(i){const amt=RUNGS[i];openSheet('<h3 style="margin:0 0 8px">'+LABELS[i]+' \u00b7 '+money(amt)+'</h3><p class="muted">From here the account must 2x to reach '+money(RUNGS[Math.min(i+1,10)])+'.</p><p>Current equity '+money(S.equity)+'. '+(S.equity>=amt?"This rung is already cleared.":money(amt-S.equity)+" still required.")+'</p><button class="btn primary" onclick="setEquity('+amt+');closeSheet()">Set equity to this rung</button>');}
function monthMatrix(year,month){const first=new Date(year,month,1);const startPad=first.getDay();const daysIn=new Date(year,month+1,0).getDate();const cells=[];for(let i=0;i<startPad;i++)cells.push(null);for(let d=1;d<=daysIn;d++)cells.push(year+"-"+String(month+1).padStart(2,"0")+"-"+String(d).padStart(2,"0"));return cells;}
function heatClass(pnl){if(!pnl)return"";const a=Math.abs(pnl);if(pnl>0)return a>400?"g3":a>120?"g2":"g1";return a>400?"r3":a>120?"r2":"r1";}
let calCursor=new Date();
function renderCal(){const y=calCursor.getFullYear(),m=calCursor.getMonth();const cells=monthMatrix(y,m);const monthDays=Object.entries(S.days).filter(([d])=>d.startsWith(y+"-"+String(m+1).padStart(2,"0")));const sum=monthDays.reduce((a,x)=>a+(x[1].pnl||0),0);const wins=monthDays.filter(x=>x[1].pnl>0).length;const losses=monthDays.filter(x=>x[1].pnl<0).length;
el("s-cal").innerHTML='<div style="display:flex;justify-content:space-between;align-items:center"><button class="btn ghost" style="width:auto" onclick="shiftCal(-1)">\u2039</button><h2 class="sec" style="margin:0">'+calCursor.toLocaleString(undefined,{month:"long",year:"numeric"})+'</h2><button class="btn ghost" style="width:auto" onclick="shiftCal(1)">\u203a</button></div><div class="hero"><div class="label">Month PnL</div><div class="equity '+cls(sum)+'" style="font-size:28px">'+signed(sum)+'</div><div class="muted">'+wins+' green \u00b7 '+losses+' red</div></div><div class="card"><div class="dow"><span>S</span><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span></div><div class="cal">'+cells.map(iso=>{if(!iso)return"<div></div>";const rec=S.days[iso];const pnl=rec?rec.pnl:null;const isT=iso===todayISO();return '<div class="cell '+heatClass(pnl||0)+' '+(isT?"today":"")+'" onclick="editDay(\''+iso+'\')">'+iso.slice(-2)+'</div>';}).join("")+'</div><div class="tiny" style="margin-top:10px">Tap a day to log or edit PnL.</div></div>';}
function shiftCal(dir){calCursor.setMonth(calCursor.getMonth()+dir);renderCal();}
function editDay(iso){const rec=S.days[iso]||{pnl:0,trades:0,note:""};openSheet('<h3 style="margin:0 0 8px">'+iso+'</h3><label class="tiny">Day PnL</label><input id="ePnl" type="number" step="0.01" value="'+(rec.pnl||0)+'" /><div style="height:8px"></div><label class="tiny">Trades</label><input id="eTr" type="number" value="'+(rec.trades||0)+'" /><div style="height:8px"></div><label class="tiny">Note</label><textarea id="eNote">'+(rec.note||"")+'</textarea><button class="btn primary" style="margin-top:10px" onclick="saveDay(\''+iso+'\')">Save day</button>');}
function saveDay(iso){const pnl=Number(el("ePnl").value||0);const trades=Number(el("eTr").value||0);const note=el("eNote").value||"";const prev=S.days[iso]?S.days[iso].pnl||0:0;S.days[iso]={pnl,trades,note};S.equity=Math.round((S.equity-prev+pnl)*100)/100;save(S);closeSheet();renderAll();}
function statsObj(){const days=dayList().filter(d=>d.pnl!==0);const wins=days.filter(d=>d.pnl>0);const losses=days.filter(d=>d.pnl<0);const gp=wins.reduce((a,d)=>a+d.pnl,0);const gl=Math.abs(losses.reduce((a,d)=>a+d.pnl,0));const wr=days.length?wins.length/days.length:0;const pf=gl?gp/gl:(gp>0?Infinity:0);const avgW=wins.length?gp/wins.length:0;const avgL=losses.length?gl/losses.length:0;let peak=S.start,eq=S.start,maxDD=0;dayList().forEach(d=>{eq+=d.pnl||0;peak=Math.max(peak,eq);maxDD=Math.max(maxDD,(peak-eq)/peak);});const best=days.reduce((a,d)=>d.pnl>(a&&a.pnl||-1e99)?d:a,null);const worst=days.reduce((a,d)=>d.pnl<(a&&a.pnl||1e99)?d:a,null);return{days:days.length,wr,pf,avgW,avgL,maxDD,best,worst,gp,gl};}
function renderStats(){const t=statsObj();el("s-stats").innerHTML='<h2 class="sec">Performance</h2><div class="row"><div class="stat"><div class="label">Win days</div><b>'+(t.wr*100).toFixed(0)+'%</b></div><div class="stat"><div class="label">Profit factor</div><b>'+(t.pf===Infinity?"inf":t.pf.toFixed(2))+'</b></div><div class="stat"><div class="label">Max DD</div><b class="down">'+(t.maxDD*100).toFixed(1)+'%</b></div></div><div class="row" style="margin-top:10px"><div class="stat"><div class="label">Avg win</div><b class="up">'+signed(t.avgW)+'</b></div><div class="stat"><div class="label">Avg loss</div><b class="down">-'+money(t.avgL)+'</b></div></div><div class="card"><h3>Expectancy</h3><p class="muted">E = (win% x avg win) - (loss% x avg loss)</p><b>'+signed((t.wr*t.avgW)-((1-t.wr)*t.avgL))+' / active day</b></div><div class="card"><h3>Outliers</h3><div class="pos"><div>Best day</div><div class="up">'+(t.best?t.best.date+" \u00b7 "+signed(t.best.pnl):"-")+'</div></div><div class="pos"><div>Worst day</div><div class="down">'+(t.worst?t.worst.date+" \u00b7 "+signed(t.worst.pnl):"-")+'</div></div><div class="pos"><div>Gross profit</div><div class="up">'+signed(t.gp)+'</div></div><div class="pos"><div>Gross loss</div><div class="down">-'+money(t.gl)+'</div></div></div><div class="card"><h3>Toward $1M</h3><p class="muted">At current 30-day average daily PnL of '+signed(rangePnl(30)/30)+', reaching $1M from '+money(S.equity)+(rangePnl(30)>0?(' takes roughly '+Math.ceil((1000000-S.equity)/Math.max(0.01,rangePnl(30)/30))+' calendar days if edge holds.'):' is not projected — edge is currently non-positive.')+'</p></div>';}
function renderMore(){el("s-more").innerHTML='<h2 class="sec">Setup</h2><div class="card"><h3>Account equity</h3><input id="eqIn" type="number" step="0.01" value="'+S.equity+'" /><button class="btn primary" style="margin-top:8px" onclick="setEquity(document.getElementById(\'eqIn\').value)">Update equity</button></div><div class="card"><h3>Lighter L1 address</h3><p class="tiny">Public account lookup. If CORS blocks the browser, paste equity manually.</p><input id="addrIn" placeholder="0x…" value="'+(S.address||"")+'" /><button class="btn" style="margin-top:8px" onclick="pullAccount()">Fetch Lighter account</button><div class="tiny" id="addrMsg" style="margin-top:8px"></div></div><div class="card"><h3>iPhone install</h3><p class="muted">Safari → Share → Add to Home Screen.</p></div><div class="card"><h3>Data</h3><button class="btn" onclick="resetDemo()">Reload demo book</button><button class="btn" style="margin-top:8px" onclick="wipeLive()">Clear to $1,000 blank book</button></div>';}
function setEquity(v){S.equity=Number(v)||S.equity;save(S);renderAll();closeSheet();}
function logToday(){const pnl=Number(el("qPnl").value||0);const trades=Number(el("qTrades").value||0);const iso=todayISO();const prev=S.days[iso]?S.days[iso].pnl||0:0;S.days[iso]={pnl,trades,note:S.days[iso]&&S.days[iso].note||""};S.equity=Math.round((S.equity-prev+pnl)*100)/100;save(S);renderAll();}
function resetDemo(){S=defaultState();save(S);renderAll();}
function wipeLive(){S=Object.assign(defaultState(),{equity:1000,realized:0,unrealized:0,days:{},positions:[]});S.days[todayISO()]={pnl:0,trades:0,note:"fresh book"};save(S);renderAll();}
async function pullAccount(){const addr=el("addrIn").value.trim();S.address=addr;save(S);const msg=el("addrMsg");msg.textContent="Looking up...";try{const r=await fetch(API+"/account?by=l1_address&value="+encodeURIComponent(addr));const j=await r.json();if(!r.ok)throw new Error(j.message||r.status);const acc=(j.accounts&&j.accounts[0])||j.account||j;const coll=Number(acc.collateral||acc.total_asset_value||0);if(coll)S.equity=coll;if(Array.isArray(acc.positions)){S.positions=acc.positions.filter(p=>Number(p.position||p.size||0)!==0).slice(0,8).map(p=>({sym:p.symbol||("M"+p.market_id),side:Number(p.sign)>=0?"long":"short",size:Math.abs(Number(p.position||0)),entry:Number(p.avg_entry_price||0),mark:Number(p.position_value||0)/Math.max(1e-9,Math.abs(Number(p.position||1))),lev:4}));}save(S);renderAll();msg.textContent="Account pulled.";}catch(e){msg.textContent="Could not pull account ("+e.message+"). Keep using local equity + calendar.";}}
async function refreshTape(){try{const r=await fetch(API+"/orderBookDetails");const j=await r.json();const want=["LIT","BTC","ETH","SOL","HYPE"];const books=j.order_book_details||[];want.forEach(s=>{const m=books.find(x=>x.symbol===s);if(m)S.tape[s]=Number(m.last_trade_price||m.mark_price);});save(S);const chip=el("liveChip");if(chip)chip.textContent="LIT "+Number(S.tape.LIT).toFixed(2);}catch(e){}}
function openSheet(html){el("sheetBody").innerHTML=html;el("sheet").classList.add("open");}
function closeSheet(){el("sheet").classList.remove("open");}
el("sheet").addEventListener("click",e=>{if(e.target.id==="sheet")closeSheet();});
function renderAll(){const map={home:renderHome,double:renderDouble,cal:renderCal,stats:renderStats,more:renderMore};const active=[].slice.call(document.querySelectorAll(".screen")).find(s=>s.classList.contains("active"));map[(active.id||"").replace("s-","")]();}
document.querySelectorAll(".tab").forEach(btn=>{btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));btn.classList.add("active");const name=btn.dataset.tab;document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id==="s-"+name));renderAll();});});
renderHome();refreshTape();setInterval(refreshTape,30000);
if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
