function liqPrice(p){var g=Number(p.liq||0);if(g>0)return g;var b=0.92/Math.max(Number(p.lev)||1,1);return p.side==="long"?p.entry*(1-b):p.entry*(1+b);}
function markOf(p){return Number(p.simMark!=null?p.simMark:p.mark);}
function distPct(p,mark){mark=mark!=null?mark:markOf(p);var liq=liqPrice(p);return ((p.side==="long"?(mark-liq):(liq-mark))/Math.max(Math.abs(mark),1e-9))*100;}
function usdToLiq(p,mark){mark=mark!=null?mark:markOf(p);return Math.abs(mark-liqPrice(p))*Math.abs(Number(p.size)||0);}
function distTone(pct){return pct<5?"danger":pct<12?"warn":"ok";}
function simFromSlider(p,t){var liq=liqPrice(p),live=Number(p.mark),span=Math.max(Math.abs(live-liq)*1.8,Math.abs(live)*0.08);return p.side==="long"?liq+span*t:liq-span*t;}
function sliderFromMark(p,mark){var liq=liqPrice(p),live=Number(p.mark),span=Math.max(Math.abs(live-liq)*1.8,Math.abs(live)*0.08);var t=p.side==="long"?(mark-liq)/span:(liq-mark)/span;return Math.max(0,Math.min(1,t));}
function posHTML(p,i){var mark=markOf(p);var pnl=(p.side==="long"?1:-1)*(mark-p.entry)*p.size;var notional=mark*p.size;var liq=liqPrice(p);var pct=distPct(p,mark);var tone=distTone(pct);var t=sliderFromMark(p,mark);var preview=p.simMark!=null?" \u00b7 preview "+money(mark):"";return '<div class="pos" data-i="'+i+'"><div class="pos-top"><div><b>'+p.sym+'</b> <span class="tag '+p.side+'">'+p.side.toUpperCase()+' '+p.lev+'x</span><div class="tiny">'+p.size+' @ '+fmt(p.entry,p.entry<20?2:1)+'</div></div><div style="text-align:right"><div class="'+cls(pnl)+'" id="pnl-'+i+'">'+signed(pnl)+'</div><div class="tiny">'+money(notional)+'</div></div></div><div class="liq"><div class="liqmeta"><span class="lp">Liq '+money(liq)+preview+'</span><span class="liqpct '+tone+'" id="pct-'+i+'">'+pct.toFixed(1)+'% away</span></div><div class="liqbar"><div class="liqtrack"><div class="liqfill '+tone+'" id="fill-'+i+'" style="width:'+(t*100).toFixed(1)+'%"></div></div><input type="range" min="0" max="1000" value="'+Math.round(t*1000)+'" data-i="'+i+'" aria-label="Distance to liquidation" /></div><div class="liqhint"><span>liquidation</span><span id="gap-'+i+'">'+money(usdToLiq(p,mark))+' buffer \u00b7 drag to stress</span></div></div></div>';}
function bindLiqBars(){document.querySelectorAll(".liqbar input").forEach(function(inp){function apply(){var i=Number(inp.dataset.i);var p=S.positions[i];if(!p)return;var t=Number(inp.value)/1000;p.simMark=simFromSlider(p,t);var mark=p.simMark;var pnl=(p.side==="long"?1:-1)*(mark-p.entry)*p.size;var pct=distPct(p,mark);var tone=distTone(pct);var fill=document.getElementById("fill-"+i);var pctEl=document.getElementById("pct-"+i);var pnlEl=document.getElementById("pnl-"+i);var gapEl=document.getElementById("gap-"+i);if(fill){fill.style.width=(t*100).toFixed(1)+"%";fill.className="liqfill "+tone;}if(pctEl){pctEl.textContent=pct.toFixed(1)+"% away";pctEl.className="liqpct "+tone;}if(pnlEl){pnlEl.textContent=signed(pnl);pnlEl.className=cls(pnl);}if(gapEl)gapEl.textContent=money(usdToLiq(p,mark))+" buffer \u00b7 "+money(mark)+" mark";}inp.addEventListener("input",apply);});}
var _renderHome=renderHome;
renderHome=function(){_renderHome();var card=document.querySelector("#s-home .card:nth-of-type(2)");if(!card)return;var html='<h3>Open positions</h3>'+(S.positions.map(posHTML).join("")||'<div class="tiny">No open positions</div>');card.innerHTML=html;bindLiqBars();};
renderHome();
